/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS
 */
public class Suhu extends javax.swing.JFrame {

    /**
     * Creates new form Suhu
     */
    public Suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton6 = new javax.swing.JRadioButton();
        InputSuhu = new javax.swing.JTextField();
        ConvertButton = new javax.swing.JButton();
        Hasil = new javax.swing.JLabel();
        Reamur1 = new javax.swing.JRadioButton();
        Kelvin1 = new javax.swing.JRadioButton();
        Farenheit1 = new javax.swing.JRadioButton();
        Celcius1 = new javax.swing.JRadioButton();
        Farenheit2 = new javax.swing.JRadioButton();
        Reamur2 = new javax.swing.JRadioButton();
        Celcius2 = new javax.swing.JRadioButton();
        Kelvin2 = new javax.swing.JRadioButton();

        jRadioButton6.setText("jRadioButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConvertButton.setText("Convert");
        ConvertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConvertButtonMouseClicked(evt);
            }
        });

        Hasil.setText("Hasil");

        Reamur1.setText("Reamur");
        Reamur1.setToolTipText("");
        Reamur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reamur1ActionPerformed(evt);
            }
        });

        Kelvin1.setText("Kelvin");
        Kelvin1.setToolTipText("");
        Kelvin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kelvin1ActionPerformed(evt);
            }
        });

        Farenheit1.setText("Farenheit");
        Farenheit1.setToolTipText("");
        Farenheit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farenheit1ActionPerformed(evt);
            }
        });

        Celcius1.setText("Celcius");
        Celcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Celcius1ActionPerformed(evt);
            }
        });

        Farenheit2.setText("Farenheit");
        Farenheit2.setToolTipText("");
        Farenheit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farenheit2ActionPerformed(evt);
            }
        });

        Reamur2.setText("Reamur");
        Reamur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reamur2ActionPerformed(evt);
            }
        });

        Celcius2.setText("Celcius");
        Celcius2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Celcius2ActionPerformed(evt);
            }
        });

        Kelvin2.setText("Kelvin");
        Kelvin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kelvin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Farenheit1)
                            .addComponent(Kelvin1)
                            .addComponent(Reamur1)
                            .addComponent(Celcius1))
                        .addGap(47, 47, 47)
                        .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Kelvin2)
                            .addComponent(Reamur2)
                            .addComponent(Celcius2)
                            .addComponent(Farenheit2))
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hasil)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(Hasil)
                                .addGap(10, 10, 10)
                                .addComponent(Farenheit2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Kelvin2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Reamur2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(ConvertButton)
                                .addGap(16, 16, 16)))
                        .addComponent(Celcius2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(InputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Farenheit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kelvin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reamur1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Celcius1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvertButtonMouseClicked
       double input = Double.parseDouble(InputSuhu.getText());
       double HslConvert;
       
//       Celcius Logic
       if(Celcius1.isSelected() && Kelvin2.isSelected()){
           HslConvert = input +273.15;
           Hasil.setText(HslConvert + " Kelvin");
       }else if(Celcius1.isSelected() && Farenheit2.isSelected()){
           HslConvert = input*1.8 + 32;
           Hasil.setText(HslConvert + " Farenheit");
       }else if(Celcius1.isSelected() && Reamur2.isSelected()){
           HslConvert = input *0.8;
           Hasil.setText(HslConvert + " Reamur");
       } else if (Celcius1.isSelected() && Celcius2.isSelected()){
           Hasil.setText(input + " Celcius");
       }
//       Farenheit Logic
       else if(Farenheit1.isSelected() && Kelvin2.isSelected()){
           HslConvert = (input+459.67)/1.8;
           Hasil.setText(HslConvert + " Kelvin");
       }else if(Farenheit1.isSelected() && Farenheit2.isSelected()){
           Hasil.setText(input + " Farenheit");
       }else if(Farenheit1.isSelected() && Reamur2.isSelected()){
           HslConvert = (input-32)/2.25;
           Hasil.setText(HslConvert + " Reamur");
       }else if (Farenheit1.isSelected() && Celcius2.isSelected()){
           HslConvert = (input-32)/1.8;
           Hasil.setText(HslConvert + " Celcius");
       }
//       Reamur Logic
       else if(Reamur1.isSelected() && Kelvin2.isSelected()){
           HslConvert = input/0.8+273.15;
           Hasil.setText(HslConvert + " Kelvin");
       }else if(Reamur1.isSelected() && Farenheit2.isSelected()){
           HslConvert = (input-7.5)*24/7+32;
           Hasil.setText(HslConvert + " Farenheit");
       }else if(Reamur1.isSelected() && Reamur2.isSelected()){
           Hasil.setText(input + " Reamur");
       }else if (Reamur1.isSelected() && Celcius2.isSelected()){
           HslConvert = input/0.8;
           Hasil.setText(HslConvert + " Celcius");
       }
//       Kelvin Logic
       else if(Kelvin1.isSelected() && Kelvin2.isSelected()){
           Hasil.setText(input + " Kelvin");
       }else if(Kelvin1.isSelected() && Farenheit2.isSelected()){
           HslConvert = input*1.8-459.67;
           Hasil.setText(HslConvert + " Farenheit");
       }else if(Kelvin1.isSelected() && Reamur2.isSelected()){
           HslConvert = (input-273.15)*0.8;
           Hasil.setText(HslConvert + " Reamur");
       }else if (Kelvin1.isSelected() && Celcius2.isSelected()){
           HslConvert = input-273.15;
           Hasil.setText(HslConvert + " Celcius");
       }
    }//GEN-LAST:event_ConvertButtonMouseClicked

    private void Farenheit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farenheit1ActionPerformed
       if(Farenheit1.isSelected()){
           Kelvin1.setSelected(false);
           Reamur1.setSelected(false);
           Celcius1.setSelected(false);
       }
    }//GEN-LAST:event_Farenheit1ActionPerformed

    private void Reamur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reamur1ActionPerformed
         if(Reamur1.isSelected()){
           Kelvin1.setSelected(false);
           Farenheit1.setSelected(false);
           Celcius1.setSelected(false);
       }
    }//GEN-LAST:event_Reamur1ActionPerformed

    private void Kelvin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kelvin1ActionPerformed
         if(Kelvin1.isSelected()){
           Reamur1.setSelected(false);
           Farenheit1.setSelected(false);
           Celcius1.setSelected(false);
       }
    }//GEN-LAST:event_Kelvin1ActionPerformed

    private void Celcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Celcius1ActionPerformed
         if(Celcius1.isSelected()){
           Kelvin1.setSelected(false);
           Farenheit1.setSelected(false);
           Reamur1.setSelected(false);
       }
    }//GEN-LAST:event_Celcius1ActionPerformed

    private void Farenheit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farenheit2ActionPerformed
        if(Farenheit2.isSelected()){
           Kelvin2.setSelected(false);
           Reamur2.setSelected(false);
           Celcius2.setSelected(false);
       }
    }//GEN-LAST:event_Farenheit2ActionPerformed

    private void Kelvin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kelvin2ActionPerformed
         if(Kelvin2.isSelected()){
           Reamur2.setSelected(false);
           Farenheit2.setSelected(false);
           Celcius2.setSelected(false);
       }
    }//GEN-LAST:event_Kelvin2ActionPerformed

    private void Reamur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reamur2ActionPerformed
         if(Reamur2.isSelected()){
           Kelvin2.setSelected(false);
           Farenheit2.setSelected(false);
           Celcius2.setSelected(false);
       }
    }//GEN-LAST:event_Reamur2ActionPerformed

    private void Celcius2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Celcius2ActionPerformed
        if(Celcius2.isSelected()){
           Kelvin2.setSelected(false);
           Farenheit2.setSelected(false);
           Reamur2.setSelected(false);
       }
    }//GEN-LAST:event_Celcius2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Celcius1;
    private javax.swing.JRadioButton Celcius2;
    private javax.swing.JButton ConvertButton;
    private javax.swing.JRadioButton Farenheit1;
    private javax.swing.JRadioButton Farenheit2;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField InputSuhu;
    private javax.swing.JRadioButton Kelvin1;
    private javax.swing.JRadioButton Kelvin2;
    private javax.swing.JRadioButton Reamur1;
    private javax.swing.JRadioButton Reamur2;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
